# Generated by Django 5.2.6 on 2025-10-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
