# Generated by Django 5.2.6 on 2025-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_title_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
