# Generated by Django 5.2.6 on 2025-10-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_userprofile_over_18_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='publisher',
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
