# Generated by Django 5.2.6 on 2025-10-24 22:02

from django.db import migrations

def create_initial_titles(apps, schema_editor):
    Title = apps.get_model('engine', 'Title')
    initial_titles = [
      {
        'name': 'Oh No!',
        'slug': 'ohno',
        'description': 'A fast-paced card game where players match cards by color or number to be the first to empty their hand.',
        'release_date': '2025-10-24',
        'category': 'card'
      },
      {
				'name': 'Four Straight',
				'slug': 'four-straight',
				'description': 'A classic board game where players take turns dropping colored discs into a vertical grid, aiming to connect four of their own discs in a row.',
				'release_date': '2025-10-24',
				'category': 'board'
			}
    ]
    for title_data in initial_titles:
        Title.objects.create(**title_data)

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_remove_title_publisher_title_category_title_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_titles),
    ]
