# Generated by Django 5.2.6 on 2025-10-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_game_gameplayer_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='invite_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='specifics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='cpu_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='is_human',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='specifics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='engine.game'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.userprofile'),
        ),
    ]
