# Generated by Django 5.2.6 on 2025-10-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_game_cancelled_at_game_invite_only_game_max_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='specifics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
