# Generated by Django 5.2.6 on 2025-10-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='details',
        ),
    ]
