# Generated by Django 5.2.6 on 2025-10-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_remove_gamelog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='last_play',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
