# Generated by Django 5.2.6 on 2025-10-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_gameplayer_last_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_slot',
            new_name='turn_order',
        ),
    ]
