# Generated by Django 5.2.6 on 2026-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_rename_current_slot_game_turn_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
